### ISSUE TITLE
点击右上角打开谱面文件夹后报错：StandaloneFileBrowserassembly:<unknown assembly> type:<unknown type> member: (null)

### ISSUE THREAD

**Issue by LostConnet** [yojohanshinwataikei/Arcade-plus#11]
**首先非常感谢开发者能开发出这样的工具！为玩家提供了极大的便利**
###  错误信息：

`StandaloneFileBrowserassembly:<unknown
assembly> type:<unknown type> member: (null)`

 Software Version:[v0.4.3](https://github.com/yojohanshinwataikei/Arcade-plus/releases/tag/v0.4.3%2B637876334131097390)

 ### 系统信息
>Device: MacBook Pro
>OS:macOS12.5
>Intel i7 9750H
>RAM:16 GB 2667 MHz DDR4
>GraphicsCard:AMD Radeon Pro 5300M 4 GB

**Comment by EternalTimes** [comment]
Same error.
>
Device: MacBook Pro
OS: 13.1 Beta (22C5044e)
Intel i7 9750H
RAM:16 GB 2667 MHz DDR4
GraphicsCard:AMD Radeon Pro 5300M 4 GB

**Comment by yojohanshinwataikei** [comment]
This should be already fixed in #7
