### ISSUE TITLE
English translation is not shown nor an option

### ISSUE THREAD

**Issue by Twinkie55** [yojohanshinwataikei/Arcade-plus#12]
...also how do i place arcs when it says "please insert a chart first"?

**Comment by 0thElement** [comment]
Hello, it does say that english translation is not available for this version of arcade.

**Comment by Twinkie55** [comment]
When you say that it's not available on THIS version what do you mean?(is there another version with the translation?)

**Comment by Fryndazs** [comment]
It's written on README.md (literally the main page).

https://github.com/yojohanshinwataikei/Arcade-plus#why-this-version-do-not-have-localisation-feature

**Comment by Twinkie55** [comment]
Yes but I wasn't aware of the meaning of this

**Comment by Twinkie55** [comment]
Back to my other question...how do you place arcs when the pop up "insert a chart first" shows (I thought I was making the chart in arcade)

**Comment by Fryndazs** [comment]
Open a chart file by clicking on "?" jacket box, you can select a ready chart folder or adding a new chart file by creating a new folder that includes blank 0.aff (New item > Text document > change the name & extension to 0.aff), a music file named with base.ogg (you can use .mp3 or .wav but I prefer .ogg), and a illust/jacket cover named base.jpg.

**Comment by Twinkie55** [comment]
Thanks, I'll check it out
