### ISSUE TITLE
Unable to open any files

### ISSUE THREAD

**Issue by pink-ichigo-tiger** [yojohanshinwataikei/Arcade-plus#8]
I received this error when I attempted to open a file on the Mac version.
![image](https://user-images.githubusercontent.com/81060181/184862821-b13d80e9-217f-4060-a6db-ef78ab267150.png)
I have a folder containing the image and the mp3 for the chart.
![image](https://user-images.githubusercontent.com/81060181/184862909-870bdcd8-d74b-4d47-91d6-a186913c4ed9.png)

**Comment by linwenxuan04** [comment]
The standalone file browser has not bind to the macOS in unity editor, waiting for the latest pull request to merge in order to solve this issue

**Comment by fengsiyuan196** [comment]
Same issue to you!
https://github.com/yojohanshinwataikei/Arcade-plus/issues/11#issue-1434052928

**Comment by yojohanshinwataikei** [comment]
This should be already fixed in #7, which will be included in the next release.
