### ISSUE TITLE
键盘快捷键突然失灵

### ISSUE THREAD

**Issue by creeper12121** [yojohanshinwataikei/Arcade-plus#9]
使用过程中所有键盘快捷键会不定期失灵，运行日志出现报错，只能通过重启Arcade恢复：
[![vobQde.png](https://s1.ax1x.com/2022/09/04/vobQde.png)](https://imgse.com/i/vobQde)

**Comment by yojohanshinwataikei** [comment]
This is a unity bug, it could be fixed in recent releases. Reopen this if the problem presist in newer version.
